### PR TITLE
feat(arc-657): bundle toast notifications

### PR DESCRIPTION
**Pull request by bartnaessens**
bundle toast notifications

placeholder werd lokaal niet vervangen, nog te verifieren

### CODE REVIEW

**Comment by bertyhell** [comment]
fixed de placeholder bug + renamed some collection naming to folders:
image

image

image

image

**Review by bertyhell — APPROVED** [review]

**Review by ian-emsens-shd — CHANGES_REQUESTED** [review]
`folders` staan niet in de [glossary](https://meemoo.atlassian.net/wiki/spaces/HA2/pages/2341404768/Glossary) 😬

**Comment by bertyhell** [comment]
image

**Review by ian-emsens-shd — APPROVED** [review]
Besproken in Slack; [de eigenlijke glossary](https://docs.google.com/spreadsheets/d/1_vGX_pBIlJeUFt7Laoj8l3iur2qw6CtdqDs-sJ1TSL0/edit#gid=0)

**Pull request merged**
