### PR TITLE
Feature/arc 252 flowplayer

### PR DESCRIPTION
**Pull request by BavoVdg**
Flowplayer component op object detail pagina.
image

### CODE REVIEW

**Comment by bertyhell** [comment]
i get this error/warning in the next console:
```
Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="/flowplayer/style/flowplayer.css"). Use Document instead.
See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
```

**Comment by bertyhell** [comment]
The background of the flowplayer section should be grey, not white:
image
image

**Comment by BavoVdg** [comment]
> i get this error/warning in the next console:
> 
> ```
> Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="/flowplayer/style/flowplayer.css"). Use Document instead.
> See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
> ```

@bertyhell Fixed in https://github.com/viaacode/hetarchief-client/pull/169

**Comment by BavoVdg** [comment]
> The background of the flowplayer section should be grey, not white: image image

Fixed

**Comment by BavoVdg** [comment]
> The background of the flowplayer section should be grey, not white: image image

Fixed!

**Review by bertyhell — APPROVED** [review]

**Pull request merged**
