### PR TITLE
Bugfix/arc 397

### PR DESCRIPTION
**Pull request by ian-emsens-shd**
- set default sorting

Wacht op backend enum sorting aanpassing, zie https://meemoo.atlassian.net/browse/ARC-397?focusedCommentId=31028

### CODE REVIEW

**Comment by ian-emsens-shd** [comment]
Waiting on https://github.com/viaacode/hetarchief-hasura/pull/120 & https://github.com/viaacode/hetarchief-proxy/pull/170

**Comment by bertyhell** [comment]
image

Something is not right with this PR

**Comment by bertyhell** [comment]
Does work correctly though, so maybe this got merged some time ago?
image

image

**Comment by ian-emsens-shd** [comment]
Probably duplicated in a different PR opened later

**Pull request merged**
